clone:
  git:
    image: plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: toolkit

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.4}-ci
    environment:
      - DOCUMENT_ROOT=/test/toolkit

pipeline:
  composer-install:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.4}-ci
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer install --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_VERSION: 1

  composer-install:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.4}-ci
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer self-update --2
      - composer install --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_VERSION: 2

  composer-update-lowest:
    group: post-prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.4}-ci
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer update --prefer-lowest --prefer-stable --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest
        COMPOSER_VERSION: 1

  composer-update-lowest:
    group: post-prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.4}-ci
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer self-update --2
      - composer update --prefer-lowest --prefer-stable --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest
        COMPOSER_VERSION: 2

  grumphp:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.4}-ci
    commands:
      - ./vendor/bin/phpcs -i
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.4}-ci
    commands:
      - ./vendor/bin/phpunit

  lint-yaml:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.4}-ci
    secrets: [ github_api_token, composer_auth ]
    commands:
      - ./vendor/bin/yaml-lint *.yml *.yml.dist
      - CONFIG_FOLDER=$(if test -d config; then find config -type f -name "*.yml"; fi)
      - if ! [ -z "$CONFIG_FOLDER" ]; then ./vendor/bin/yaml-lint $CONFIG_FOLDER; fi
      - LIB_FOLDER=$(if test -d lib; then find lib -type f -name "*.yml"; fi)
      - if ! [ -z "$LIB_FOLDER" ]; then ./vendor/bin/yaml-lint $LIB_FOLDER; fi

  lint-php:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.4}-ci
    secrets: [ github_api_token, composer_auth ]
    commands:
      - ./vendor/bin/parallel-lint --exclude web --exclude vendor -e module -e inc -e theme -e install -e php .

matrix:
  PHP_VERSION:
    - 7.3
    - 7.4
  COMPOSER_BOUNDARY:
    - lowest
    - highest
  COMPOSER_VERSION:
    - 1
    - 2
