clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next

workspace:
  base: /test
  path: toolkit

matrix:
  PHP_VERSION:
    - 8.1
    - 8.2
  COMPOSER_VERSION:
    - 2
  COMPOSER_BOUNDARY:
    - lowest
    - highest

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    environment: &env
      - DOCUMENT_ROOT=/test/toolkit

pipeline:
  composer-install:
    group: composer
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    secrets: [ github_api_token, gitlab_api_token, composer_auth ]
    environment: *env
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer self-update --${COMPOSER_VERSION}
      - composer install --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  composer-update-lowest:
    group: composer
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    secrets: [ github_api_token, gitlab_api_token, composer_auth ]
    environment: *env
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer self-update --${COMPOSER_VERSION}
      - composer update --prefer-lowest --prefer-stable --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  phpcs:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    environment: *env
    commands:
      - ./run toolkit:test-phpcs

  phpmd:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    environment: *env
    commands:
      - ./run toolkit:test-phpmd --files=src/,tests/

  phpunit:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    secrets: [ qa_api_basic_auth, github_api_token, gitlab_api_token, composer_auth, asda_user, asda_password, nextcloud_user, nextcloud_pass ]
    environment: *env
    commands:
      - ./run toolkit:test-phpunit

  lint-yaml:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    secrets: [ github_api_token, composer_auth ]
    environment: *env
    commands:
      - ./run toolkit:lint-yaml

  lint-php:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    secrets: [ github_api_token, composer_auth ]
    environment: *env
    commands:
      - ./run toolkit:lint-php
