clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next

workspace:
  base: /test
  path: toolkit

matrix:
  include:
    #- PHP_VERSION: 7.3
    #  PHING_OPTS: -logger phing.listener.AnsiColorLogger
    #  BUILD_OPTIONS: -D'platform.package.version'='2.6' -D'profile'='multisite_drupal_standard'
    - PHP_VERSION: 7.4
      PHING_OPTS: -logger phing.listener.AnsiColorLogger
      BUILD_OPTIONS: -D'platform.package.version'='2.6' -D'profile'='multisite_drupal_standard'
      ASDA_PROJECT_ID: comm-cwt2019
    #- PHP_VERSION: 7.3
    #  PHING_OPTS: -logger phing.listener.AnsiColorLogger
    #  BUILD_OPTIONS: -D'profile'='drupal' -D'profile.name'='minimal' -D'profile.core'='7.85'
    - PHP_VERSION: 7.4
      PHING_OPTS: -logger phing.listener.AnsiColorLogger
      BUILD_OPTIONS: -D'profile'='drupal' -D'profile.name'='minimal' -D'profile.core'='7.85'
      ASDA_PROJECT_ID: comm-cwt2019

# ==============================================================================
# Main services
# ==============================================================================
services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    detach: true
    environment:
      - DOCUMENT_ROOT=/test/toolkit/build
  selenium:
    image: registry.fpfis.eu/fpfis/selenium:standalone-chrome-${SELENIUM_VERSION=3.141.59-20210913}
    shm_size: 2gb
    environment:
      - JAVA_OPTS=-Dselenium.LOGGER.level=WARNING
    detach: true
  mysql:
    image: registry.fpfis.eu/fpfis/sql:percona-${MYSQL_VERSION=5.7}
    detach: true
    command: --innodb-log-file_size=2G --max-allowed-packet=1G --innodb-buffer-pool-size=512M --wait-timeout=31536000
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  solr:
    image: registry.fpfis.eu/fpfis/solr:5
    detach: true

pipeline:
  setup:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    group: setup
    secrets: [ github_api_token ]
    commands:
      - composer self-update --1
      - PROJECT=$(pwd) composer toolkit-install
      - rm -rf ./.tmp/ ./build
      - cp ./includes/phing/props/drone.props build.develop.props
      - ./toolkit/phing project-properties-validate ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}/${PHP_VERSION}:/cache

  build:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    group: build
    secrets: [ github_api_token ]
    commands:
      - composer self-update --1
      - ./toolkit/phing build-platform build-subsite-dev ${BUILD_OPTIONS} ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}/${PHP_VERSION}:/cache

  asda-nextcloud:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    secrets: [ github_api_token, composer_auth, asda_user, asda_password, nextcloud_user, nextcloud_pass ]
    group: asda-nextcloud
    commands:
      - ./toolkit/phing cache-clear-global
      - ./toolkit/phing project-database-download -Dproject.id=${ASDA_PROJECT_ID} -Ddb.dl.type=nextcloud ${PHING_OPTS}
      - ./toolkit/phing project-asda-date -Dproject.id=${ASDA_PROJECT_ID} ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}/${PHP_VERSION}:/cache

  asda-default:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    secrets: [ github_api_token, composer_auth, asda_user, asda_password, nextcloud_user, nextcloud_pass ]
    group: asda-default
    commands:
      - ./toolkit/phing cache-clear-global
      - ./toolkit/phing project-database-download -Dproject.id=${ASDA_PROJECT_ID} ${PHING_OPTS}
      - ./toolkit/phing project-asda-date -Dproject.id=${ASDA_PROJECT_ID} ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}/${PHP_VERSION}:/cache

  install-clean:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    group: install-clean
    secrets: [ github_api_token ]
    commands:
      - composer self-update --1
      - ./toolkit/phing build-platform build-subsite-dev ${BUILD_OPTIONS} ${PHING_OPTS}
      - ./toolkit/phing install-clean ${BUILD_OPTIONS} ${PHING_OPTS}
      - ./toolkit/phing drush-gdpr-dump -D'database-file'='/test/toolkit/dump.sql' ${BUILD_OPTIONS} ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}/${PHP_VERSION}:/cache

  install-clone:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    group: install-clone
    secrets: [ github_api_token ]
    commands:
      - composer self-update --1
      - ./toolkit/phing build-platform build-subsite-dev ${BUILD_OPTIONS} ${PHING_OPTS}
      - ./toolkit/phing install-clone -D'project.db.file'='/test/toolkit/dump.sql.gz' ${BUILD_OPTIONS} ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}/${PHP_VERSION}:/cache

  smoketest:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    group: smoke-tests
    secrets: [ github_api_token ]
    commands:
      - composer self-update --1
      - ./toolkit/phing drush-run-smoketest ${BUILD_OPTIONS} ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}/${PHP_VERSION}:/cache

  behat:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    group: coding-standards
    secrets: [ github_api_token ]
    commands:
      - composer self-update --1
      - ./toolkit/phing test-run-behat ${BUILD_OPTIONS} ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}/${PHP_VERSION}:/cache

  phpcs:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    group: coding-standards
    secrets: [ github_api_token ]
    commands:
      - composer self-update --1
      - touch /test/toolkit/composer.lock
      - ./toolkit/phing test-run-phpcs ${BUILD_OPTIONS} ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}/${PHP_VERSION}:/cache

  php7-comp:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    group: coding-standards
    secrets: [ github_api_token ]
    commands:
      - composer self-update --1
      - ./toolkit/phing test-run-phpcs-compatibility -D'phpcs.compat.checkreturn'='false' ${BUILD_OPTIONS} ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}/${PHP_VERSION}:/cache

  create-distribution:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    group: create-distribution
    secrets: [ github_api_token ]
    commands:
      - composer self-update --1
      - ./toolkit/phing create-distribution ${BUILD_OPTIONS} ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}/${PHP_VERSION}:/cache

  git-hooks:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    group: git-hooks
    secrets: [ github_api_token ]
    commands:
      - composer self-update --1
      - ./toolkit/phing git-hook-enable ${BUILD_OPTIONS} ${PHING_OPTS}
      - ./toolkit/phing git-hook-disable ${BUILD_OPTIONS} ${PHING_OPTS}
      - ./toolkit/phing git-hook-enable ${BUILD_OPTIONS} ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}/${PHP_VERSION}:/cache
