workspace:
  base: /test
  path: ssk

services:
  web:
    image: fpfis/php56-dev
    environment:
     - DOCUMENT_ROOT=/test/ssk/build
  mysql:
    image: fpfis/mysql56
#  ecas:
#    image: fpfis-acpcloud622hotmail.azurecr.io/ecas
  selenium:
    image: selenium/standalone-chrome
    environment:
      - SE_OPTS=-log /tmp/selenium.log
#  solr:
#    image: fpfis/solr5

pipeline:

  prepare-php:
    group: prepare
    image: fpfis/php56-dev
    commands:
      - composer update
#      - ./ssk/phing
    volumes:
      - /cache:/cache

  build-dev:
    image: fpfis/php56-dev
    commands:
      - ./ssk/phing project-build-platform
      - ./ssk/phing build-subsite-dev
    volumes:
      - /cache:/cache

  install:
    image: fpfis/php56-dev
    commands:
      - ./ssk/phing install-project-clean -D'db.host'='mysql' -D'db.name'=database
    volumes:
      - /cache:/cache

  test:
    image: fpfis/php56-dev
    commands:
      - ./ssk/phing test-run-behat
    volumes:
      - /cache:/cache

  build-dist:
    image: fpfis/php56-dev
    commands:
      - ./ssk/phing build-platform-dist -D'composer.bin'=$(which composer)
      - tar -czf ${DRONE_REPO_NAME}-${DRONE_TAG}.tar.gz -C build .
    when:
      event: tag

  github_release:
    image: plugins/github-release
    files:
      - ${DRONE_REPO_NAME}-${DRONE_TAG}.tar.gz
    checksum:
      - sha1
      - sha256
      - sha512
    secrets: [ GITHUB_RELEASE_API_KEY ]
    when:
      event: tag
