workspace:
  base: /test
  path: toolkit

services:
  web:
    image: fpfis/php56-dev
    environment:
     - DOCUMENT_ROOT=/test/toolkit/build
  mysql:
    image: fpfis/mysql56
  selenium:
    image: selenium/standalone-chrome
    environment:
      - SE_OPTS=-log /tmp/selenium.log
  solr:
    image: fpfis/solr5

pipeline:
  toolkit:
    image: fpfis/php56-dev
    commands:
      - PROJECT=$(pwd) composer toolkit-install
      - ./toolkit/phing project-properties-validate
    volumes:
      - /cache:/cache

  build:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing build-project-platform
      - ./toolkit/phing build-subsite-dev
    volumes:
      - /cache:/cache

  install:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing install-project-clean
    volumes:
      - /cache:/cache

  test:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing test-run-behat
    volumes:
      - /cache:/cache
