clone:
  git:
    image: plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: toolkit

services:
  web:
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    environment:
      - DOCUMENT_ROOT=/test/toolkit

pipeline:
  composer-install:
    group: prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer install --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_VERSION: 1

  composer-install:
    group: prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer self-update --2
      - composer install --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_VERSION: 2

  composer-update-lowest:
    group: post-prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer update --prefer-lowest --prefer-stable --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest
        COMPOSER_VERSION: 1

  composer-update-lowest:
    group: post-prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer self-update --2
      - composer update --prefer-lowest --prefer-stable --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest
        COMPOSER_VERSION: 2

  grumphp:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    commands:
      - ./vendor/bin/phpunit

matrix:
  PHP_VERSION:
    - 7.3
    - 7.4
  COMPOSER_BOUNDARY:
    - lowest
    - highest
  COMPOSER_VERSION:
    - 1
    - 2
