clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next

branches: [ feature/*, release/* ]

workspace:
  base: /test
  path: toolkit

matrix:
  PHP_VERSION:
    - 8.1
    - 8.2
  COMPOSER_VERSION:
    - 2
  COMPOSER_BOUNDARY:
    - lowest
    - highest

pipeline:
  composer-install:
    group: composer
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    secrets: [ github_api_token, gitlab_api_token, composer_auth ]
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer self-update --${COMPOSER_VERSION}
      - composer install --ansi --no-progress
      - composer outdated --no-dev --locked --direct --minor-only
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  composer-update-lowest:
    group: composer
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    secrets: [ github_api_token, gitlab_api_token, composer_auth ]
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer self-update --${COMPOSER_VERSION}
      - composer update --prefer-lowest --prefer-stable --ansi --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  phpcs:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    commands:
      - ./run toolkit:test-phpcs

  phpmd:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    commands:
      - ./run toolkit:test-phpmd --files=src/,tests/

  phpunit:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    secrets: [ qa_api_basic_auth, qa_api_auth_token, github_api_token, gitlab_api_token, composer_auth, asda_user, asda_password, nextcloud_user, nextcloud_pass, toolkit_mock_repo ]
    commands:
      - ./run toolkit:test-phpunit --execution=parallel

  lint-yaml:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    secrets: [ github_api_token, composer_auth ]
    commands:
      - ./run toolkit:lint-yaml

  lint-php:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    secrets: [ github_api_token, composer_auth ]
    commands:
      - ./run toolkit:lint-php

  phpstan:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    commands:
      - ./run toolkit:test-phpstan
