#!/bin/sh
#
# Automatically adds branch name and branch description to every commit message.


branchPath=$(git symbolic-ref -q HEAD) #Somthing like refs/heads/myBranchName
branchName=${branchPath##*/}      #Get text behind the last / of the branch path

firstLine=$(head -n1 $1)
error_msg="Aborting commit, your commit message is missing an ID (XYZ-123, #123)."

commit_regex='([A-Z]-[0-9]+|#[0-9])'

touch .branchNameFile
echo $branchName > .branchNameFile


if ! grep -iqE "$commit_regex" "$1"; then
  if grep -iqE "$commit_regex" .branchNameFile; then
    if ! [ -z "$firstLine"  ] ;then #Check that this is not an amend by checking that the first line is empty
      echo "$branchName: $firstLine" > "$1" #Insert branch name at the start of the commit message file
    fi
  fi
fi

if ! grep -iqE "$commit_regex" "$1"; then
   echo "$error_msg" >&2
   exit 1
fi

rm .branchNameFile >&2

