<?php

/**
 * @file
 * This file contains helper hooks and code to improve the development.
 */

module_load_include('inc', 'toolkit_dev', 'toolkit_dev.features_field_base');

/**
 * Implements hook_COMPONENT_alter().
 *
 * Here we unlock all the fields when they are inserted into the database.
 */
function toolkit_dev_field_default_field_bases_alter(&$fields) {
  foreach ($fields as &$field) {
    if (isset($field['locked'])) {
      $field['locked'] = 0;
    }
  }
}

/**
 * Implements hook_features_api_alter().
 */
function toolkit_dev_features_api_alter(&$components) {
  if (isset($components['field_base'])) {
    $components['field_base']['base'] = '_toolkit_dev_field_base';
  }
}

/**
 * Implements hook_features_export_alter().
 *
 * Add the standard info file requirements. And remove unwanted items.
 */
function toolkit_dev_features_export_alter(&$export, $module_name) {
  $export['php'] = '5.6';
  $export['multisite_version'] = '2.4';
  unset($export['project']);
  unset($export['version']);
}
