#!/bin/bash

# Set variables if needed.
FILENAME=$(basename $0)
if [ $FILENAME != "dbash" ]; then
  export BUILD_ID_UNIQUE=${FILENAME#ssk-}
  export WORKSPACE=$(pwd)
fi

# Get correct script path.
pushd . > /dev/null
SCRIPT_PATH="${BASH_SOURCE[0]}";
if ([ -h "${SCRIPT_PATH}" ]) then
  while([ -h "${SCRIPT_PATH}" ]) do
    cd `dirname "$SCRIPT_PATH"`;
    SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`;
  done
fi
cd `dirname ${SCRIPT_PATH}` > /dev/null
SCRIPT_PATH=`pwd`;
popd  > /dev/null

# Execute with docker-compose.
$(which docker-compose) -p ${BUILD_ID_UNIQUE} -f ${SCRIPT_PATH}/docker-compose.yml $@

# Remove symlink if we are executing down.
if [ "$1" = "down" ]; then
  rm -f ssk-${BUILD_ID_UNIQUE}
fi
