gitleaks:
  repo: https://github.com/gitleaks/gitleaks
  tag: 8.27.2
  sha256: 141c3b2dede46d8b3a53b47116da756bd223decc0374797559a6b50ecba5590c
  os: linux_x64
  options: '--no-banner -v --no-git --follow-symlinks'
  ignore-file: '.leaksignore'
  report-to-file: false
  fields:
    - File
    - Fingerprint
    - ToolkitFingerprint
