toolkit:
  project_id: toolkit
  tmp_folder: '/cache'
  clean:
    config_file: 'config/sync/core.extension.yml'
  clone:
    dumpfile: 'mysql.gz'
    # Nextcloud supports the following services: mysql, virtuoso, solr.
    asda_services: 'mysql'
    asda_type: 'nextcloud'
    asda_url: 'webgate.ec.europa.eu/fpfis/files-for/automate_dumps/${toolkit.project_id}'
    nextcloud_url: 'files.fpfis.tech.ec.europa.eu/remote.php/dav/files'
    nextcloud_admin: false
    asda_vendor: 'ec-europa'
    asda_source: 'reference'
    myloader: '/scripts/importdb.sh'
    mydumper: '/scripts/backupdb.sh'
  forbidden_files:
    - name: ".env"
      error: ".env file detected!\n In order to avoid loading .env file in ACC or PROD environments, please rename it to something like .env.dist\n The file belongs to your application. You should guarantee that is not being called into any point of your Drupal site. If you are only calling it in docker-compose.yml, it's recommended to drop entirely the file and declare the environment variables straight into docker-compose.yml file."
    - name: "grumphp.yml.dist"
      error: "The grumphp.yml.dist file was detected but the package is not being required by your project, please remove the file."
      condition_callback: 'EcEuropa\Toolkit\Callbacks\ForbiddenFilesConditions::grumpPhpisNotInstalled'
  components:
    outdated:
      check: true
      # Ignore packages in specific version, example:
      # - name: drupal/webform
      #   version: 1.1.1
      ignores: [ ]
    abandoned:
      check: true
    unsupported:
      check: true
    composer:
      drupal_patches: true
      scripts:
        forbidden:
          post-root-package-install:
            - "Subsite\\composer\\SetupWizard::setup"
          post-install-cmd:
            - "DrupalComposer\\DrupalScaffold\\Plugin::scaffold"
    docker_compose:
      environment_variables:
        forbidden:
          - ASDA_USER
          - ASDA_PASSWORD
          - QA_API_BASIC_AUTH
  deploy:
    sequence_file: '.opts.yml'
    sequence_key: 'upgrade_commands'
  install:
    clone:
      commands: [ ]
  build:
    dist:
      root: 'dist'
      keep:
        - ${drupal.root}
        - config
        - vendor
        - composer.lock
        - composer.json
      remove:
        - CHANGELOG.md
        - CHANGELOG.txt
        - COPYRIGHT.txt
        - INSTALL.mysql.txt
        - INSTALL.pgsql.txt
        - install.php
        - INSTALL.sqlite.txt
        - INSTALL.txt
        - LICENSE.txt
        - MAINTAINERS.txt
        - UPDATE.txt
        - README.txt
      commands: [ ]
    dev:
      commands: [ ]
    htaccess:
      block:
        file-match: '(README\.(md|txt)|CHANGELOG\.(md|txt))$'
    custom-code-folder: 'lib'
    npm:
      theme-task-runner: grunt
      packages: grunt grunt-contrib-jshint grunt-contrib-watch grunt-contrib-sass grunt-contrib-clean grunt-contrib-uglify
  scss:
    validate: 'false'
  invalid-versions:
    - 1.x
    - 2.x
  install_dependencies: true
  patches:
    dir: resources/patches
    composer: composer.json
    # Set to true when using cweagans/composer-patches:^2, this will
    # allow patches from dependencies to be listed and downloaded.
    dependencies: false
  hooks:
    # A relative path from the project root where the hooks are located.
    dir: 'resources/git/hooks'
    active:
      # Check for modified files and run PHPcs.
      - pre-commit
      # Check if the commit message is properly formatted.
      - commit-msg
      # Run the PHPcs and linters (configurable).
      - pre-push
    commit-msg:
      example: 'AB1C-123: The commit message.'
      conditions:
        - message: 'The commit message must start with the JIRA issue number.'
          regex: /^[A-Z0-9]+\-\d+/
        - message: 'The JIRA issue number must be followed by a colon and space.'
          regex: /^[A-Z0-9]+\-\d+:\ /
        - message: 'The subject must start with capital letter.'
          regex: /^[A-Z0-9]+\-\d+:\ [A-Z]/
        - message: 'The commit message must end with a period.'
          regex: /\.$/
    pre-push:
      commands:
        - toolkit:test-phpcs
        - toolkit:test-phpmd
        - toolkit:lint-php
        - toolkit:opts-review
