toolkit:
  tmp_folder: '/cache'
  clean:
    config_file: 'config/sync/core.extension.yml'
  clone:
    dumpfile: 'mysql.gz'
    # Nextcloud supports the following services: mysql, virtuoso, solr.
    asda_services: 'mysql'
    asda_type: 'nextcloud'
    asda_url: 'webgate.ec.europa.eu/fpfis/files-for/automate_dumps/${toolkit.project_id}'
    nextcloud_url: 'files.fpfis.tech.ec.europa.eu/remote.php/dav/files'
    nextcloud_admin: false
    asda_vendor: 'ec-europa'
    asda_source: 'reference'
    myloader: '/scripts/importdb.sh'
    mydumper: '/scripts/backupdb.sh'
  components:
    outdated:
      check: true
  deploy:
    config_file: 'config/sync/core.extension.yml'
    sequence_file: '.opts.yml'
    sequence_key: 'upgrade_commands'
  install:
    clone:
      commands: [ ]
  build:
    dist:
      root: 'dist'
      keep:
        - ${drupal.root}
        - config
        - vendor
        - composer.lock
        - composer.json
      remove:
        - CHANGELOG.txt
        - COPYRIGHT.txt
        - INSTALL.mysql.txt
        - INSTALL.pgsql.txt
        - install.php
        - INSTALL.sqlite.txt
        - INSTALL.txt
        - LICENSE.txt
        - MAINTAINERS.txt
        - UPDATE.txt
        - README.txt
      commands: [ ]
    dev:
      commands: [ ]
    custom-code-folder: 'lib'
    npm:
      theme-task-runner: grunt
      packages: grunt grunt-contrib-jshint grunt-contrib-watch grunt-contrib-sass grunt-contrib-clean grunt-contrib-uglify
  scss:
    validate: 'false'
  invalid-versions:
    - 1.x
    - 2.x
  hooks:
    # A relative path from the project root where the hooks are located.
    dir: 'resources/git/hooks'
    active:
      # Check for modified files and run PHPcs.
      - pre-commit
      # Check if the commit message is properly formatted.
      - prepare-commit-msg
      # Run the PHPcs and linters (configurable).
      - pre-push
    prepare-commit-msg:
      example: 'ABC-123: The commit message.'
      conditions:
        - message: 'The commit message must start with the JIRA issue number.'
          regex: /^[A-Z]+\-\d+/
        - message: 'The JIRA issue number must be followed by a colon and space.'
          regex: /^[A-Z]+\-\d+:\ /
        - message: 'The subject must start with capital letter.'
          regex: /^[A-Z]+\-\d+:\ [A-Z]/
        - message: 'The commit message must end with a period.'
          regex: /\.$/
    pre-push:
      commands:
        - toolkit:test-phpcs
        - toolkit:test-phpmd
        - toolkit:lint-php
        - toolkit:opts-review
