toolkit:
  test:
    behat:
      from: behat.yml.dist
      to: behat.yml
      profile: default
      options: 'strict'
      commands:
        before: [ ]
        after: [ ]
    phpunit:
      options: ''
      execution: default
      from: phpunit.xml.dist
      to: phpunit.xml
      testsuite: ~
      group: ~
      covers: ~
      uses: ~
      filter: ~
      printer: EcEuropa\Toolkit\Tests\TestDurationPrinter
      commands:
        before: [ ]
        after: [ ]
    blackfire:
      uuid:
      pages:
        - '/'
        - '/user'
    phpcs:
      mode: phpcs
      config: phpcs.xml
      ignore_annotations: false
      show_sniffs: false
      standards:
        - ./vendor/drupal/coder/coder_sniffer/Drupal
        - ./vendor/drupal/coder/coder_sniffer/DrupalPractice
        - ./vendor/ec-europa/qa-automation/phpcs/QualityAssurance
      ignore_patterns:
        - ${toolkit.build.dist.root}/
        - .cache/
        - vendor/
        - web/
        - node_modules/
        - config/
        - '*.min.css'
        - '*.min.js'
      triggered_by:
        - php
        - module
        - inc
        - theme
        - profile
        - install
        - yml
      files:
        - ./lib
        - ./resources
        - ./src
    phpmd:
      config: phpmd.xml
      format: ansi
      ignore_patterns:
        - ${toolkit.build.dist.root}/
        - .cache/
        - vendor/
        - web/
        - node_modules/
        - config/
      triggered_by:
        - php
        - module
        - inc
        - theme
        - install
      files:
        - lib
        - src
    phpstan:
      config: phpstan.neon
      level: '1'
      includes:
        - vendor/mglaman/phpstan-drupal/extension.neon
        - vendor/mglaman/phpstan-drupal/rules.neon
        - vendor/phpstan/phpstan-deprecation-rules/rules.neon
      ignore_errors:
        - "#^Unsafe usage of new static#"
      files: [ lib, src ]
      ignores: [ ${toolkit.build.dist.root}, .cache, vendor ]
      memory_limit: ''
      options: ''
  lint:
    eslint:
      config: .eslintrc.json
      packages: 'eslint-config-drupal eslint-plugin-yml'
      ignores: [ '${toolkit.build.dist.root}/*', '.cache/*', 'vendor/*', 'web/*', 'dist/*' ]
      extensions_yaml: [ '.yml', '.yaml' ]
      options_yaml: ''
      extensions_js: [ '.js' ]
      options_js: ''
    php:
      extensions: [ 'php', 'module', 'inc', 'theme', 'install' ]
      exclude: [ '${toolkit.build.dist.root}/', '.cache/', 'vendor/', 'web/' ]
      options: ''
