Search.appendIndex(
    [
                {
            "fqsen": "\\OpenEuropa\\Site\\Tests\\Behat\\BlackfireMinkContext",
            "name": "BlackfireMinkContext",
            "summary": "Extends\u0020Behat\u0020MinkContext\u0020and\u0020add\u0020steps\u0020from\u0020Drupal\u0020MinkContext.",
            "url": "classes/OpenEuropa-Site-Tests-Behat-BlackfireMinkContext.html"
        },                {
            "fqsen": "\\OpenEuropa\\Site\\Tests\\Behat\\BlackfireMinkContext\u003A\u003AassertAtPath\u0028\u0029",
            "name": "assertAtPath",
            "summary": "Visit\u0020a\u0020given\u0020path,\u0020and\u0020additionally\u0020check\u0020for\u0020HTTP\u0020response\u0020code\u0020200.",
            "url": "classes/OpenEuropa-Site-Tests-Behat-BlackfireMinkContext.html#method_assertAtPath"
        },                {
            "fqsen": "\\OpenEuropa\\Site\\Tests\\Behat\\BlackfireMinkContext\u003A\u003AassertTextVisible\u0028\u0029",
            "name": "assertTextVisible",
            "summary": "",
            "url": "classes/OpenEuropa-Site-Tests-Behat-BlackfireMinkContext.html#method_assertTextVisible"
        },                {
            "fqsen": "\\OpenEuropa\\Site\\Tests\\Behat\\BlackfireMinkContext\u003A\u003AassertNotTextVisible\u0028\u0029",
            "name": "assertNotTextVisible",
            "summary": "",
            "url": "classes/OpenEuropa-Site-Tests-Behat-BlackfireMinkContext.html#method_assertNotTextVisible"
        },                {
            "fqsen": "\\OpenEuropa\\Site\\Tests\\Behat\\BlackfireMinkContext\u003A\u003AassertHttpResponse\u0028\u0029",
            "name": "assertHttpResponse",
            "summary": "",
            "url": "classes/OpenEuropa-Site-Tests-Behat-BlackfireMinkContext.html#method_assertHttpResponse"
        },                {
            "fqsen": "\\OpenEuropa\\Site\\Tests\\Behat\\BlackfireMinkContext\u003A\u003AassertNotHttpResponse\u0028\u0029",
            "name": "assertNotHttpResponse",
            "summary": "",
            "url": "classes/OpenEuropa-Site-Tests-Behat-BlackfireMinkContext.html#method_assertNotHttpResponse"
        },                {
            "fqsen": "\\OpenEuropa\\Site\\Tests\\Behat\\BlackfireMinkContext\u003A\u003ApressButton\u0028\u0029",
            "name": "pressButton",
            "summary": "Presses\u0020button\u0020with\u0020specified\u0020id\u007Cname\u007Ctitle\u007Calt\u007Cvalue.",
            "url": "classes/OpenEuropa-Site-Tests-Behat-BlackfireMinkContext.html#method_pressButton"
        },                {
            "fqsen": "\\OpenEuropa\\Site\\Tests\\Behat\\BlackfireMinkContext\u003A\u003AassertHeading\u0028\u0029",
            "name": "assertHeading",
            "summary": "",
            "url": "classes/OpenEuropa-Site-Tests-Behat-BlackfireMinkContext.html#method_assertHeading"
        },                {
            "fqsen": "\\OpenEuropa\\Site\\Tests\\Behat\\BlackfireMinkContext\u003A\u003AassertRegionLinkFollow\u0028\u0029",
            "name": "assertRegionLinkFollow",
            "summary": "",
            "url": "classes/OpenEuropa-Site-Tests-Behat-BlackfireMinkContext.html#method_assertRegionLinkFollow"
        },                {
            "fqsen": "\\OpenEuropa\\Site\\Tests\\Behat\\BlackfireMinkContext\u003A\u003AiAmOnLandingPage\u0028\u0029",
            "name": "iAmOnLandingPage",
            "summary": "This\u0020is\u0020the\u0020example\u0020provided\u0020by\u0020Blackfire\u0020docs.",
            "url": "classes/OpenEuropa-Site-Tests-Behat-BlackfireMinkContext.html#method_iAmOnLandingPage"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\BuildCommands",
            "name": "BuildCommands",
            "summary": "Provides\u0020commands\u0020to\u0020build\u0020a\u0020site\u0020for\u0020development\u0020and\u0020a\u0020production\u0020artifact.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-BuildCommands.html"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\BuildCommands\u003A\u003AgetConfigurationFile\u0028\u0029",
            "name": "getConfigurationFile",
            "summary": "\u007B\u0040inheritdoc\u007D",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-BuildCommands.html#method_getConfigurationFile"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\BuildCommands\u003A\u003AbuildDist\u0028\u0029",
            "name": "buildDist",
            "summary": "Build\u0020the\u0020distribution\u0020package.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-BuildCommands.html#method_buildDist"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\BuildCommands\u003A\u003AbuildDev\u0028\u0029",
            "name": "buildDev",
            "summary": "Build\u0020site\u0020for\u0020local\u0020development.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-BuildCommands.html#method_buildDev"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\BuildCommands\u003A\u003AbuildDevReset\u0028\u0029",
            "name": "buildDevReset",
            "summary": "Build\u0020site\u0020for\u0020local\u0020development\u0020from\u0020scratch\u0020with\u0020a\u0020clean\u0020git.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-BuildCommands.html#method_buildDevReset"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\BuildCommands\u003A\u003AgetGitTag\u0028\u0029",
            "name": "getGitTag",
            "summary": "Returns\u0020the\u0020current\u0020Git\u0020tag.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-BuildCommands.html#method_getGitTag"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\BuildCommands\u003A\u003AgetGitCommitHash\u0028\u0029",
            "name": "getGitCommitHash",
            "summary": "Returns\u0020the\u0020current\u0020Git\u0020commit\u0020hash.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-BuildCommands.html#method_getGitCommitHash"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\BuildCommands\u003A\u003AbuildAssets\u0028\u0029",
            "name": "buildAssets",
            "summary": "Build\u0020theme\u0020assets\u0020\u0028Css\u0020and\u0020Js\u0029.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-BuildCommands.html#method_buildAssets"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\CloneCommands",
            "name": "CloneCommands",
            "summary": "Provides\u0020commands\u0020to\u0020clone\u0020a\u0020site\u0020for\u0020development\u0020and\u0020a\u0020production\u0020artifact.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-CloneCommands.html"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\CloneCommands\u003A\u003AgetConfigurationFile\u0028\u0029",
            "name": "getConfigurationFile",
            "summary": "\u007B\u0040inheritdoc\u007D",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-CloneCommands.html#method_getConfigurationFile"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\CloneCommands\u003A\u003ArunDeploy\u0028\u0029",
            "name": "runDeploy",
            "summary": "Run\u0020deployment\u0020sequence.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-CloneCommands.html#method_runDeploy"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\CloneCommands\u003A\u003AinstallDump\u0028\u0029",
            "name": "installDump",
            "summary": "Import\u0020the\u0020production\u0020snapshot.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-CloneCommands.html#method_installDump"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\CloneCommands\u003A\u003AdownloadDump\u0028\u0029",
            "name": "downloadDump",
            "summary": "Download\u0020ASDA\u0020snapshot.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-CloneCommands.html#method_downloadDump"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\CloneCommands\u003A\u003AcheckForNewerDump\u0028\u0029",
            "name": "checkForNewerDump",
            "summary": "Check\u0020if\u0020a\u0020newer\u0020dump\u0020exists\u0020on\u0020the\u0020server.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-CloneCommands.html#method_checkForNewerDump"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\CloneCommands\u003A\u003AasdaProcessFile\u0028\u0029",
            "name": "asdaProcessFile",
            "summary": "Helper\u0020to\u0020download\u0020and\u0020process\u0020a\u0020ASDA\u0020file.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-CloneCommands.html#method_asdaProcessFile"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\CloneCommands\u003A\u003AgenerateAsdaWgetInputFile\u0028\u0029",
            "name": "generateAsdaWgetInputFile",
            "summary": "Create\u0020file\u0020containing\u0020a\u0020url\u0020for\u0020usage\u0020in\u0020wget\u0020\u002D\u002Dinput\u002Dfile\u0020argument.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-CloneCommands.html#method_generateAsdaWgetInputFile"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\CloneCommands\u003A\u003AwgetDownloadFile\u0028\u0029",
            "name": "wgetDownloadFile",
            "summary": "Download\u0020the\u0020file\u0020present\u0020in\u0020the\u0020tmp\u0020file.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-CloneCommands.html#method_wgetDownloadFile"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\CloneCommands\u003A\u003AtmpDirectory\u0028\u0029",
            "name": "tmpDirectory",
            "summary": "Return\u0020the\u0020tmp\u0020folder\u0020path,\u0020folder\u0020is\u0020created\u0020if\u0020missing.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-CloneCommands.html#method_tmpDirectory"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\DrupalCommands",
            "name": "DrupalCommands",
            "summary": "Drupal\u0020commands\u0020to\u0020setup\u0020and\u0020install\u0020a\u0020Drupal\u00208\u0020site.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-DrupalCommands.html"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\DrupalCommands\u003A\u003AsettingsSetup\u0028\u0029",
            "name": "settingsSetup",
            "summary": "Setup\u0020Drupal\u0020settings.php\u0020file\u0020in\u0020compliance\u0020with\u0020Toolkit\u0020conventions.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-DrupalCommands.html#method_settingsSetup"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\DrupalCommands\u003A\u003AgetSettingsBlockRegex\u0028\u0029",
            "name": "getSettingsBlockRegex",
            "summary": "Remove\u0020settings\u0020block\u0020from\u0020given\u0020content.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-DrupalCommands.html#method_getSettingsBlockRegex"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\DrupalCommands\u003A\u003AgetToolkitSettingsBlock\u0028\u0029",
            "name": "getToolkitSettingsBlock",
            "summary": "Helper\u0020function\u0020to\u0020update\u0020settings.php\u0020file.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-DrupalCommands.html#method_getToolkitSettingsBlock"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\DrupalCommands\u003A\u003A\u0024blockEnd",
            "name": "blockEnd",
            "summary": "Comment\u0020ending\u0020the\u0020Toolkit\u0020settings\u0020block.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-DrupalCommands.html#property_blockEnd"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\DrupalCommands\u003A\u003A\u0024blockStart",
            "name": "blockStart",
            "summary": "Comment\u0020starting\u0020the\u0020Toolkit\u0020settings\u0020block.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-DrupalCommands.html#property_blockStart"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\InstallCommands",
            "name": "InstallCommands",
            "summary": "Class\u0020ToolkitCommands.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-InstallCommands.html"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\InstallCommands\u003A\u003AgetConfigurationFile\u0028\u0029",
            "name": "getConfigurationFile",
            "summary": "\u007B\u0040inheritdoc\u007D",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-InstallCommands.html#method_getConfigurationFile"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\InstallCommands\u003A\u003AinstallClean\u0028\u0029",
            "name": "installClean",
            "summary": "Install\u0020a\u0020clean\u0020website.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-InstallCommands.html#method_installClean"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\InstallCommands\u003A\u003AinstallClone\u0028\u0029",
            "name": "installClone",
            "summary": "Install\u0020a\u0020clone\u0020website.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-InstallCommands.html#method_installClone"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\InstallCommands\u003A\u003AimportConfig\u0028\u0029",
            "name": "importConfig",
            "summary": "Import\u0020config.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-InstallCommands.html#method_importConfig"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\LoadDefaultConfigCommands",
            "name": "LoadDefaultConfigCommands",
            "summary": "Default\u0020configuration\u0020loader.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-LoadDefaultConfigCommands.html"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\LoadDefaultConfigCommands\u003A\u003AgetDefaultConfigurationFile\u0028\u0029",
            "name": "getDefaultConfigurationFile",
            "summary": "Path\u0020to\u0020YAML\u0020configuration\u0020file\u0020containing\u0020command\u0020defaults.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-LoadDefaultConfigCommands.html#method_getDefaultConfigurationFile"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\LoadDefaultConfigCommands\u003A\u003AloadDefaultConfig\u0028\u0029",
            "name": "loadDefaultConfig",
            "summary": "Load\u0020default\u0020Toolkit\u0020configuration.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-LoadDefaultConfigCommands.html#method_loadDefaultConfig"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\TestsCommands",
            "name": "TestsCommands",
            "summary": "Class\u0020TestsCommands.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-TestsCommands.html"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\TestsCommands\u003A\u003AgetConfigurationFile\u0028\u0029",
            "name": "getConfigurationFile",
            "summary": "\u007B\u0040inheritdoc\u007D",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-TestsCommands.html#method_getConfigurationFile"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\TestsCommands\u003A\u003AtoolkitSetupPhpcs\u0028\u0029",
            "name": "toolkitSetupPhpcs",
            "summary": "Setup\u0020PHP\u0020code\u0020sniffer\u0020for\u0020standalone\u0020execution.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-TestsCommands.html#method_toolkitSetupPhpcs"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\TestsCommands\u003A\u003AtoolkitPhpcs\u0028\u0029",
            "name": "toolkitPhpcs",
            "summary": "Run\u0020PHP\u0020code\u0020sniffer.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-TestsCommands.html#method_toolkitPhpcs"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\TestsCommands\u003A\u003AtoolkitPhpmd\u0028\u0029",
            "name": "toolkitPhpmd",
            "summary": "Run\u0020PHPMD\u0020standalone.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-TestsCommands.html#method_toolkitPhpmd"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\TestsCommands\u003A\u003ArunGrumphp\u0028\u0029",
            "name": "runGrumphp",
            "summary": "Run\u0020PHP\u0020code\u0020sniffer\u0020within\u0020GrumPHP.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-TestsCommands.html#method_runGrumphp"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\TestsCommands\u003A\u003ArunPhpcs\u0028\u0029",
            "name": "runPhpcs",
            "summary": "Run\u0020PHP\u0020code\u0020sniffer\u0020in\u0020standalone\u0020mode.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-TestsCommands.html#method_runPhpcs"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\TestsCommands\u003A\u003AcheckPhpCsRequirements\u0028\u0029",
            "name": "checkPhpCsRequirements",
            "summary": "Make\u0020sure\u0020that\u0020the\u0020config\u0020file\u0020exists\u0020and\u0020configuration\u0020is\u0020correct.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-TestsCommands.html#method_checkPhpCsRequirements"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\TestsCommands\u003A\u003AtoolkitBehat\u0028\u0029",
            "name": "toolkitBehat",
            "summary": "Run\u0020Behat\u0020tests.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-TestsCommands.html#method_toolkitBehat"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\TestsCommands\u003A\u003AtoolkitPhpUnit\u0028\u0029",
            "name": "toolkitPhpUnit",
            "summary": "Run\u0020PHPUnit\u0020tests.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-TestsCommands.html#method_toolkitPhpUnit"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\TestsCommands\u003A\u003AtoolkitPhpcbf\u0028\u0029",
            "name": "toolkitPhpcbf",
            "summary": "Run\u0020PHP\u0020code\u0020autofixing.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-TestsCommands.html#method_toolkitPhpcbf"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\TestsCommands\u003A\u003AtoolkitPhpcbfStandalone\u0028\u0029",
            "name": "toolkitPhpcbfStandalone",
            "summary": "Run\u0020PHP\u0020code\u0020autofixing\u0020in\u0020standalone\u0020mode.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-TestsCommands.html#method_toolkitPhpcbfStandalone"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\TestsCommands\u003A\u003AtoolkitLintYaml\u0028\u0029",
            "name": "toolkitLintYaml",
            "summary": "Run\u0020lint\u0020YAML.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-TestsCommands.html#method_toolkitLintYaml"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\TestsCommands\u003A\u003AtoolkitLintPhp\u0028\u0029",
            "name": "toolkitLintPhp",
            "summary": "Run\u0020lint\u0020PHP.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-TestsCommands.html#method_toolkitLintPhp"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\TestsCommands\u003A\u003AtoolkitBlackfire\u0028\u0029",
            "name": "toolkitBlackfire",
            "summary": "Run\u0020Blackfire.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-TestsCommands.html#method_toolkitBlackfire"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands",
            "name": "ToolCommands",
            "summary": "Generic\u0020tools.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AgetConfigurationFile\u0028\u0029",
            "name": "getConfigurationFile",
            "summary": "\u007B\u0040inheritdoc\u007D",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_getConfigurationFile"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AdisableDrupalCache\u0028\u0029",
            "name": "disableDrupalCache",
            "summary": "Disable\u0020aggregation\u0020and\u0020clear\u0020cache.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_disableDrupalCache"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AdisplayNotifications\u0028\u0029",
            "name": "displayNotifications",
            "summary": "Display\u0020toolkit\u0020notifications.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_displayNotifications"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AcomponentCheck\u0028\u0029",
            "name": "componentCheck",
            "summary": "Check\u0020composer.json\u0020for\u0020components\u0020that\u0020are\u0020not\u0020whitelisted\/blacklisted.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_componentCheck"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AprintComponentResults\u0028\u0029",
            "name": "printComponentResults",
            "summary": "Helper\u0020function\u0020to\u0020validate\u0020the\u0020component.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_printComponentResults"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AvalidateComponent\u0028\u0029",
            "name": "validateComponent",
            "summary": "Helper\u0020function\u0020to\u0020validate\u0020the\u0020component.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_validateComponent"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AcomponentMandatory\u0028\u0029",
            "name": "componentMandatory",
            "summary": "Helper\u0020function\u0020to\u0020check\u0020component\u0027s\u0020review\u0020information.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_componentMandatory"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AcomponentRecommended\u0028\u0029",
            "name": "componentRecommended",
            "summary": "Helper\u0020function\u0020to\u0020check\u0020component\u0027s\u0020review\u0020information.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_componentRecommended"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AcomponentInsecure\u0028\u0029",
            "name": "componentInsecure",
            "summary": "Helper\u0020function\u0020to\u0020check\u0020component\u0027s\u0020review\u0020information.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_componentInsecure"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AcomponentOutdated\u0028\u0029",
            "name": "componentOutdated",
            "summary": "Helper\u0020function\u0020to\u0020check\u0020component\u0027s\u0020review\u0020information.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_componentOutdated"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AgetQaEndpointContent\u0028\u0029",
            "name": "getQaEndpointContent",
            "summary": "Curl\u0020function\u0020to\u0020access\u0020endpoint\u0020with\u0020or\u0020without\u0020authentication.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_getQaEndpointContent"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AgetQaSessionToken\u0028\u0029",
            "name": "getQaSessionToken",
            "summary": "Helper\u0020to\u0020return\u0020the\u0020session\u0020token.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_getQaSessionToken"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003ApostQaContent\u0028\u0029",
            "name": "postQaContent",
            "summary": "Helper\u0020to\u0020send\u0020a\u0020payload\u0020to\u0020the\u0020QA\u0020Website.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_postQaContent"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003Ad9Compatibility\u0028\u0029",
            "name": "d9Compatibility",
            "summary": "Check\u0020project\u0020compatibility\u0020for\u0020Drupal\u00209\u0020upgrade.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_d9Compatibility"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AcomposerLockCheck\u0028\u0029",
            "name": "composerLockCheck",
            "summary": "Check\u0020if\u0020\u0027composer.lock\u0027\u0020exists\u0020on\u0020the\u0020project\u0020root\u0020folder.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_composerLockCheck"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AoptsReview\u0028\u0029",
            "name": "optsReview",
            "summary": "Check\u0020project\u0027s\u0020.opts.yml\u0020file\u0020for\u0020forbidden\u0020commands.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_optsReview"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AcheckCommitMessage\u0028\u0029",
            "name": "checkCommitMessage",
            "summary": "Check\u0020the\u0020commit\u0020message\u0020for\u0020SKIPPING\u0020tokens.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_checkCommitMessage"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AsetupBlackfireBehat\u0028\u0029",
            "name": "setupBlackfireBehat",
            "summary": "Copy\u0020the\u0020needed\u0020resources\u0020to\u0020run\u0020Behat\u0020with\u0020Blackfire.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_setupBlackfireBehat"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AgetPackageDetails\u0028\u0029",
            "name": "getPackageDetails",
            "summary": "Call\u0020release\u0020history\u0020of\u0020d.org\u0020to\u0020confirm\u0020security\u0020alert.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_getPackageDetails"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AtoolkitRequirements\u0028\u0029",
            "name": "toolkitRequirements",
            "summary": "Check\u0020the\u0020Toolkit\u0020Requirements.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_toolkitRequirements"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AfixPermissions\u0028\u0029",
            "name": "fixPermissions",
            "summary": "Run\u0020script\u0020to\u0020fix\u0020permissions\u0020\u0028experimental\u0029.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_fixPermissions"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AtoolkitVersion\u0028\u0029",
            "name": "toolkitVersion",
            "summary": "Check\u0020the\u0020Toolkit\u0020version.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_toolkitVersion"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AgetPackagePropertyFromComposer\u0028\u0029",
            "name": "getPackagePropertyFromComposer",
            "summary": "Helper\u0020to\u0020return\u0020a\u0020property\u0020from\u0020a\u0020package\u0020in\u0020the\u0020composer.lock\u0020file.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_getPackagePropertyFromComposer"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AtoolkitVendorList\u0028\u0029",
            "name": "toolkitVendorList",
            "summary": "Check\u0020\u0027Vendor\u0027\u0020packages\u0020being\u0020monitorised.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_toolkitVendorList"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AgetQaApiBasicAuth\u0028\u0029",
            "name": "getQaApiBasicAuth",
            "summary": "Return\u0020the\u0020QA\u0020API\u0020BASIC\u0020AUTH\u0020from\u0020token\u0020or\u0020from\u0020questions.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_getQaApiBasicAuth"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AgetDeploymentEnvironment\u0028\u0029",
            "name": "getDeploymentEnvironment",
            "summary": "Returns\u0020the\u0020current\u0020environment\u0020based\u0020on\u0020env\u0020vars.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_getDeploymentEnvironment"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AtoolkitCodeReview\u0028\u0029",
            "name": "toolkitCodeReview",
            "summary": "This\u0020command\u0020will\u0020execute\u0020all\u0020the\u0020testing\u0020tools.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_toolkitCodeReview"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AformatBytes\u0028\u0029",
            "name": "formatBytes",
            "summary": "Helper\u0020to\u0020convert\u0020bytes\u0020to\u0020human\u002Dreadable\u0020unit.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_formatBytes"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands\\ToolCommands\u003A\u003AgetQaProjectInformation\u0028\u0029",
            "name": "getQaProjectInformation",
            "summary": "Returns\u0020the\u0020Project\u0020information\u0020from\u0020the\u0020QA\u0020Website.",
            "url": "classes/EcEuropa-Toolkit-TaskRunner-Commands-ToolCommands.html#method_getQaProjectInformation"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\Toolkit",
            "name": "Toolkit",
            "summary": "Provides\u0020default\u0020Toolkit\u0020class.",
            "url": "classes/EcEuropa-Toolkit-Toolkit.html"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\Toolkit\u003A\u003AgetQaWebsiteUrl\u0028\u0029",
            "name": "getQaWebsiteUrl",
            "summary": "Returns\u0020the\u0020QA\u0020base\u0020url.",
            "url": "classes/EcEuropa-Toolkit-Toolkit.html#method_getQaWebsiteUrl"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\Toolkit\u003A\u003AisCiCd\u0028\u0029",
            "name": "isCiCd",
            "summary": "Returns\u0020whether\u0020is\u0020running\u0020in\u0020CI\/CD\u0020environment.",
            "url": "classes/EcEuropa-Toolkit-Toolkit.html#method_isCiCd"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\Toolkit\u003A\u003AgetAsdaUser\u0028\u0029",
            "name": "getAsdaUser",
            "summary": "Returns\u0020the\u0020ASDA\u0020user.",
            "url": "classes/EcEuropa-Toolkit-Toolkit.html#method_getAsdaUser"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\Toolkit\u003A\u003AgetAsdaPass\u0028\u0029",
            "name": "getAsdaPass",
            "summary": "Returns\u0020the\u0020ASDA\u0020password.",
            "url": "classes/EcEuropa-Toolkit-Toolkit.html#method_getAsdaPass"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\Toolkit\u003A\u003AgetNextcloudUser\u0028\u0029",
            "name": "getNextcloudUser",
            "summary": "Returns\u0020the\u0020NEXTCLOUD\u0020user.",
            "url": "classes/EcEuropa-Toolkit-Toolkit.html#method_getNextcloudUser"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\Toolkit\u003A\u003AgetNextcloudPass\u0028\u0029",
            "name": "getNextcloudPass",
            "summary": "Returns\u0020the\u0020NEXTCLOUD\u0020password.",
            "url": "classes/EcEuropa-Toolkit-Toolkit.html#method_getNextcloudPass"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\Toolkit\u003A\u003AVERSION",
            "name": "VERSION",
            "summary": "Constant\u0020holding\u0020the\u0020current\u0020version.",
            "url": "classes/EcEuropa-Toolkit-Toolkit.html#constant_VERSION"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\OpenEuropa\\Site\\Tests\\Behat",
            "name": "Behat",
            "summary": "",
            "url": "namespaces/openeuropa-site-tests-behat.html"
        },                {
            "fqsen": "\\OpenEuropa\\Site\\Tests",
            "name": "Tests",
            "summary": "",
            "url": "namespaces/openeuropa-site-tests.html"
        },                {
            "fqsen": "\\OpenEuropa\\Site",
            "name": "Site",
            "summary": "",
            "url": "namespaces/openeuropa-site.html"
        },                {
            "fqsen": "\\OpenEuropa",
            "name": "OpenEuropa",
            "summary": "",
            "url": "namespaces/openeuropa.html"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner\\Commands",
            "name": "Commands",
            "summary": "",
            "url": "namespaces/eceuropa-toolkit-taskrunner-commands.html"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit\\TaskRunner",
            "name": "TaskRunner",
            "summary": "",
            "url": "namespaces/eceuropa-toolkit-taskrunner.html"
        },                {
            "fqsen": "\\EcEuropa\\Toolkit",
            "name": "Toolkit",
            "summary": "",
            "url": "namespaces/eceuropa-toolkit.html"
        },                {
            "fqsen": "\\EcEuropa",
            "name": "EcEuropa",
            "summary": "",
            "url": "namespaces/eceuropa.html"
        }            ]
);
