command:
  toolkit:
    generate-documentation:
      options:
        token: ${env.GITHUB_API_TOKEN}
        repo: 'https://%s@github.com/joaocsilva/toolkit'
        docs-dir: docs
        tmp-dir: docs_tmp
        branch: documentation
