command:
  toolkit:
    install-clean:
      options:
        config-file: ${toolkit.clean.config_file}
    run-deploy:
      options:
        sequence-file: ${toolkit.deploy.sequence_file}
        sequence-key: ${toolkit.deploy.sequence_key}
        config-file: ${toolkit.deploy.config_file}
