command:
  toolkit:
    install-clean:
      options:
        config-file: ${toolkit.clean.config_file}
    install-clone:
      options:
        dumpfile: ${toolkit.clone.dumpfile}
    run-deploy:
      options:
        sequence-file: ${toolkit.deploy.sequence_file}
        sequence-key: ${toolkit.deploy.sequence_key}
        append: ${toolkit.deploy.append}
