command:
  toolkit:
    code-review:
      options:
        phpcs: false
        opts-review: false
        lint-php: false
        lint-yaml: false
        phpstan: false
    install-dependencies:
      options:
        print: false
