name: 'Toolkit testing pipeline'

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  pull-requests: read

env:
  DOCUMENT_ROOT: /test/toolkit
  QA_API_AUTH_TOKEN: ${{ secrets.QA_API_AUTH_TOKEN }}
  TOOLKIT_MOCK_REPO: ${{ secrets.TOOLKIT_MOCK_REPO }}
  GITHUB_API_TOKEN: ${{ secrets.API_TOKEN }}

jobs:
  code-review:
    runs-on: ubuntu-latest
    container: registry.fpfis.eu/digit/devsecops/httpd-php:8.3-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Composer
        run: |
          composer validate
          composer install --no-ansi --no-interaction

      - name: test-clone
        run: |
          git clone "$TOOLKIT_MOCK_REPO" test
          ls -la test || echo 'fail'
          ls -la test/api || echo 'fail'

      - name: PHPcs
        run: ./vendor/bin/run toolkit:test-phpcs

      - name: PHPmd
        run: ./vendor/bin/run toolkit:test-phpmd --files=src/,tests/

      - name: Lint PHP
        run: ./vendor/bin/run toolkit:lint-php

      - name: PHPStan
        run: ./vendor/bin/run toolkit:test-phpstan

      - name: Lint Yaml
        run: ./vendor/bin/run toolkit:lint-yaml

      - name: Lint CSpell
        run: ./vendor/bin/run toolkit:lint-cspell --files=src --config=resources/cspell/.cspell.json

      - name: PHPUnit
        run: |
          mkdir -p /test/toolkit
          cp -r $GITHUB_WORKSPACE/* /test/toolkit
          ./vendor/bin/run toolkit:test-phpunit --working-dir=/test/toolkit --execution=parallel
