name: 'Testing pipeline'

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  pull-requests: read

env:
  DOCUMENT_ROOT: /__w/toolkit/toolkit
  QA_API_AUTH_TOKEN: ${{ secrets.QA_API_AUTH_TOKEN }}
  TOOLKIT_MOCK_REPO: ${{ secrets.TOOLKIT_MOCK_REPO }}
  GITHUB_API_TOKEN: ${{ secrets.API_TOKEN }}

jobs:
  Testing:
    runs-on: ubuntu-latest
    container: fpfis/httpd-php:${{ matrix.php_version }}-ci
    strategy:
      matrix:
        php_version: [ 8.2, 8.3, 8.4 ]
        composer_boundary: [ highest, lowest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Composer
        shell: bash
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          composer validate
          if [ ${{ matrix.composer_boundary }} == "highest" ]; then
            composer install --no-ansi --no-progress --no-interaction
          else
            composer update --prefer-lowest --prefer-stable --no-ansi --no-progress --no-interaction
          fi

      - name: PHPcs
        run: ./run toolkit:test-phpcs

      - name: PHPmd
        run: ./run toolkit:test-phpmd --files=src/,tests/

      - name: PHPStan
        run: ./run toolkit:test-phpstan

      - name: Lint PHP
        run: ./run toolkit:lint-php

      - name: Lint Yaml
        run: ./run toolkit:lint-yaml

      - name: Lint CSpell
        run: ./run toolkit:lint-cspell --files=src --config=resources/cspell/.cspell.json

      - name: PHPUnit
        shell: bash
        run: ./run toolkit:test-phpunit --execution=parallel
