name: 'Documentation pipeline'

on:
  workflow_dispatch:
  workflow_call:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  Documentation:
    runs-on: ubuntu-latest
    container: fpfis/httpd-php:8.3-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Composer
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          composer validate
          composer install --prefer-dist --no-ansi --no-progress --no-interaction

      - name: Generate documentation
        run: ./run toolkit:generate-documentation --token=${{ secrets.API_TOKEN }} --push || echo "skip"
