#!/bin/sh
#
# Called by "git commit" with the name of the file that has the commit message,
# followed by the description of the commit message's source. If the hook fails
# with a non-zero status, the commit is aborted.
#
# This hook will enforce the conditions defined in the configuration
# toolkit.hooks.commit-msg.conditions.
#

# Check if running corporate docker image fpfis/httpd-php.
SERVICE=$(docker compose ps 2>/dev/null | grep 'fpfis/httpd-php' | awk '{ print $4 }')
# Prefix with the docker compose exec if running docker.
PREFIX=$([ "$SERVICE" ] && echo "docker compose exec -T $SERVICE ./vendor/bin/run" || echo './vendor/bin/run')
# Call the hook.
$PREFIX toolkit:hooks-run `basename "$0"` "$1" "$2"
