#!/bin/sh
#
# Called by "git commit" with no arguments. The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the commit.
#
# This hook should execute the PHPcs against the modified files.
#

./vendor/bin/run toolkit:hooks-run `basename "$0"`
