#!/bin/sh
#
# Called by "git push" after it has checked the remote status, but before
# anything has been pushed. Receives two arguments, the name of the remote,
# followed by the remote url. If this script exits with a non-zero status
# nothing will be pushed.
#
# This hook will execute the commands defined in the configuration
# toolkit.hooks.pre-push.commands.
#

# Detect docker-compose or docker compose.
DC=$(docker compose version 2>/dev/null | grep -q 'version' && echo 'docker compose' || echo 'docker-compose')
# Check if running corporate docker image fpfis/httpd-php.
SERVICE=$($DC ps 2>/dev/null | grep 'fpfis/httpd-php' | awk '{ print $4 }')
# Prefix with the docker compose exec if running docker.
PREFIX=$([ "$SERVICE" ] && echo "$DC exec -T $SERVICE ./vendor/bin/run" || echo './vendor/bin/run')
# Call the hook.
$PREFIX toolkit:hooks-run `basename "$0"` "$1" "$2"
