#!/bin/sh
#
# Called by "git commit" with the name of the file that has the commit message,
# followed by the description of the commit message's source. If the hook fails
# with a non-zero status, the commit is aborted.
#
# This hook will enforce the conditions defined in the configuration
# toolkit.hooks.prepare-commit-msg.conditions.
#

./vendor/bin/run toolkit:hooks-run `basename "$0"` $1 $2
